src/objects/Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Offered__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Offered</label>
        <referenceTo>Program_Offered__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>Application-{0000}</displayFormat>
        <label>Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Education_History__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Education Histories</relationshipLabel>
        <relationshipName>Education_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <referenceTo>School__c</referenceTo>
        <relationshipLabel>Education Histories</relationshipLabel>
        <relationshipName>Education_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Education History</label>
    <nameField>
        <displayFormat>EDU - {0000}</displayFormat>
        <label>Education  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Histories</pluralLabel>
    <recordTypes>
        <fullName>College</fullName>
        <active>true</active>
        <label>College</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Family__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Family</relationshipLabel>
        <relationshipName>Family</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passport_Country_of_Issue__c</fullName>
        <label>Passport Country of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ÅLAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA (al-Djazāʼir)</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BONAIRE, ST. EUSTATIUS, AND SABA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Passport_Expiration_Date__c</fullName>
        <label>Passport Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Passport_Number__c</fullName>
        <label>Passport Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program_Offered__c.object
<CustomObject>
    <label>Program Offered</label>
    <nameField>
        <label>Program Offered Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs Offered</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/School__c.object
<CustomObject>
    <fields>
        <fullName>School_City__c</fullName>
        <label>School City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_State__c</fullName>
        <label>School State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <recordTypes>
        <fullName>College</fullName>
        <active>true</active>
        <label>College</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject>
    <fields>
        <fullName>INTLSemester__c</fullName>
        <label>INTLSemester</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fall (August)</fullName>
                </value>
                <value>
                    <fullName>Spring (January)</fullName>
                </value>
                <value>
                    <fullName>Summer (May)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Semester__c</fullName>
        <label>Semester</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fall</fullName>
                </value>
                <value>
                    <fullName>Spring</fullName>
                </value>
                <value>
                    <fullName>Summer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2015</fullName>
                </value>
                <value>
                    <fullName>2016</fullName>
                </value>
                <value>
                    <fullName>2017</fullName>
                </value>
                <value>
                    <fullName>2018</fullName>
                </value>
                <value>
                    <fullName>2019</fullName>
                </value>
                <value>
                    <fullName>2020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Term</label>
    <nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NGD_CommunityMyApplicationController.cls
public class NGD_CommunityMyApplicationController{
	//sobject
	public String contactJSON{get;set;}
	public String applicationJSON{get;set;}
	public String applicationsJSON{get;set;}
	public String highSchoolEHJSON{get;set;}
	public String collegesEHJSON{get;set;}
	public String familiesJSON{get;set;}

	//describe
	public String contactDescribeJSON{get;set;}
	public String applicationDescribeJSON{get;set;}
	public String termDescribeJSON{get;set;}
	public String educationHistoryDescribeJSON{get;set;}
	public String familyDescribeJSON{get;set;}

	//record type
    public static Id highSchoolEHRTId{get{return [select id from RecordType where Name='High School' and SobjectType='Education_History__c'].id;}set;}
    public static Id collegeEHRTId{get{return [select id from RecordType where Name='College' and SobjectType='Education_History__c'].id;}set;}
    public static Id highSchoolRTId{get{return [select id from RecordType where Name='High School' and SobjectType='School__c'].id;}set;}
    public static Id collegeRTId{get{return [select id from RecordType where Name='College' and SobjectType='School__c'].id;}set;}

	public NGD_CommunityMyApplicationController(NGD_DataController dataCtrl){
		Map<String, String> mapWhereClause = new Map<String, String>();
		Set<String> customFields = new Set<String>();

		//contact
		mapWhereClause.clear();
		customFields.clear();
		mapWhereClause.put('Id=', NGD_Utility.getCurrentContactId());

    sObject contact=(sObject)NGD_Utility.getObjectWithFields('Contact', mapWhereClause, null,null, customFields, NGD_Constant.RequiredFieldTypes.ALL_FIELDS_WITH_CUSTOM_FIELDS)[0];
		contactJSON=String.escapeSingleQuotes(JSON.serialize(contact));

		//application
	  mapWhereClause.clear();
	  customFields.clear();
		customFields.add('Program_Offered__r.Id');
		customFields.add('Program_Offered__r.Name');
		customFields.add('Term__r.Id');
		customFields.add('Term__r.Name');
		customFields.add('Term__r.Year__c');
		customFields.add('Term__r.INTLSemester__c');
		customFields.add('Term__r.Semester__c');
	  mapWhereClause.put('Contact__c=', (Id)contact.get('Id'));

		List<sObject> applications=(List<sObject>)NGD_Utility.getObjectWithFields('Application__c', mapWhereClause, 'Order By Name',null, customFields, NGD_Constant.RequiredFieldTypes.ALL_FIELDS_WITH_CUSTOM_FIELDS);

    //if application selected
    String appId=ApexPages.currentPage().getParameters().get('id');
    if (!String.isBlank(appId)){
        ////application
			mapWhereClause.clear();
			customFields.clear();
			mapWhereClause.put('Id=', appId);
			customFields.add('Program_Offered__r.Id');
			customFields.add('Program_Offered__r.Name');

			sObject application=(sObject)NGD_Utility.getObjectWithFields('Application__c', mapWhereClause, null,null, customFields, NGD_Constant.RequiredFieldTypes.ALL_FIELDS_WITH_CUSTOM_FIELDS)[0];
			applicationJSON=String.escapeSingleQuotes(JSON.serialize(application));

			////education history
			Education_History__c highSchoolEH;
			List<Education_History__c> collegesEH=new List<Education_History__c>();

			mapWhereClause.clear();
			customFields.clear();
			mapWhereClause.put('Application__c=', appId);
			customFields.add('School__r.Id');
			customFields.add('School__r.Name');
			customFields.add('School__r.School_City__c');
			customFields.add('School__r.School_State__c');
			List<Education_History__c> educationHistories=(List<Education_History__c>)NGD_Utility.getObjectWithFields('Education_History__c', mapWhereClause, 'Order By Name',null, customFields, NGD_Constant.RequiredFieldTypes.ALL_FIELDS_WITH_CUSTOM_FIELDS);

			for (Education_History__c eh:educationHistories){
				if(eh.RecordTypeId==highSchoolEHRTId)
				highSchoolEH=eh;
				if(eh.RecordTypeId==collegeEHRTId)
				collegesEH.add(eh);
			}
			highSchoolEHJSON=String.escapeSingleQuotes(JSON.serialize(highSchoolEH));
			collegesEHJSON=String.escapeSingleQuotes(JSON.serialize(collegesEH));

			//family
			List<Family__c> families=[select Relationship__c,First_Name__c,Last_Name__c,Passport_Country_of_Issue__c,Passport_Number__c,Passport_Expiration_Date__c from Family__c where Application__c=:appId];
			familiesJSON=String.escapeSingleQuotes(JSON.serialize(families));

		}

		//describe
			////contactDescribe
			contactDescribeJSON=String.escapeSingleQuotes(NGD_DataController.describe('Contact'));
			////applicationDescribe
			applicationDescribeJSON=String.escapeSingleQuotes(NGD_DataController.describe('Application__c'));
			////termDescribe
			termDescribeJSON=String.escapeSingleQuotes(NGD_DataController.describe('Term__c'));
			////educationHistoryDescribe
			educationHistoryDescribeJSON=String.escapeSingleQuotes(NGD_DataController.describe('Education_History__c'));
			////familyDescribe
			familyDescribeJSON=String.escapeSingleQuotes(NGD_DataController.describe('Family__c'));

			contactJSON=String.escapeSingleQuotes(JSON.serialize(contact));
			applicationsJSON=String.escapeSingleQuotes(JSON.serialize(applications));

	}
 }