src/objects/Assignment_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Assignment Queue</label>
    <nameField>
        <label>Assignment Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Queue_Member__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Queue__c</fullName>
        <label>Assignment Queue</label>
        <referenceTo>Assignment_Queue__c</referenceTo>
        <relationshipLabel>Assignment Queue Members</relationshipLabel>
        <relationshipName>Assignment_Queue_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Assignment_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assignment Queue Member</label>
    <nameField>
        <displayFormat>Member-{0000}</displayFormat>
        <label>Assignment Queue Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assignment Queue Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assignment_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Object__c</fullName>
        <label>Related Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Assignment Rule</label>
    <nameField>
        <label>Assignment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Assignment_Rule_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_Rule__c</fullName>
        <label>Assignment Rule</label>
        <referenceTo>Assignment_Rule__c</referenceTo>
        <relationshipLabel>Assignment Rule Entries</relationshipLabel>
        <relationshipName>Assignment_Rule_Entries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Assignment Rule Entry</label>
    <nameField>
        <label>Assignment Rule Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Rule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Lightning_ASGMT_DataControllerTest.cls
@isTest
private class Lightning_ASGMT_DataControllerTest {

		@isTest static void test_method_one() {
				Profile p=[select id from Profile where Name='System Administrator' limit 1];

				User user = new User();
				user.Username ='unitTestDante@unitTestDante.com';
				user.LastName = 'unitTestDante';
				user.Email = 'unitTestDante@unitTestDante.com';
				user.alias = 'uTest';
				user.TimeZoneSidKey = 'America/Chicago';
				user.LocaleSidKey = 'en_US';
				user.ProfileId=p.id;
				user.EmailEncodingKey = 'ISO-8859-1';
				user.LanguageLocaleKey = 'en_US';
				user.isActive=true;
				insert user;

				Assignment_Rule__c ar=new Assignment_Rule__c();
				ar.Name='Assignment Rule UnitTest';
				ar.Related_Object__c='Contact';
				ar.Active__c=true;
				insert ar;

				Assignment_Rule_Entry__c re=new Assignment_Rule_Entry__c();
				re.Order__c=1;
				re.Name='Assignment Rule Entry UnitTest';
				re.Assignment_Rule__c=ar.Id;
				insert re;

				Assignment_Queue__c aq=new Assignment_Queue__c();
				aq.Name='Assignment Queue UnitTest';
				insert aq;

				Assignment_Queue_Member__c aqm=new Assignment_Queue_Member__c();
				aqm.Assignment_Queue__c=aq.Id;
				aqm.Member_Active__c=true;
				aqm.User__c=user.Id;
				insert aqm;

				// Implement test code
				Lightning_ASGMT_DataController.getConfig();

				Lightning_ASGMT_DataController.getAssignmentRuleObjectOptions();

				String paramsJson='{"ruleId":"'+ ar.Id +'","isRuleActive":true,"ruleRelatedObject":"Contact"}';
				Lightning_ASGMT_DataController.getPagedResult(ar.getSObjectType().getDescribe().getName(),null,null,null,paramsJson);

				paramsJson='{"ruleEntryId":"'+ re.Id +'","ruleEntryOldOrder":"2"}';
				Lightning_ASGMT_DataController.getPagedResult(re.getSObjectType().getDescribe().getName(),null,null,null,paramsJson);

				paramsJson='{"partialWhereClause":"'+ Lightning_Utility.nameSpacePrefix +'Assignment_Queue__c=\''+ aq.Id +'\' AND "}';
				Lightning_ASGMT_DataController.getPagedResult(aqm.getSObjectType().getDescribe().getName(),null,null,null,paramsJson);

				Lightning_ASGMT_DataController.updateRuleEntryOrder(re.Id,'2');

				Lightning_ASGMT_DataController.validateRelatedObject('Contact');

				Lightning_Utility.getObjectNameBasedOnPrefix(ar.Id);
				Lightning_Utility.getNameSpacePerfix('__');

				List<SObject> sObjectList=new List<SObject>();
				sObjectList.add(ar);
				Lightning_Utility.getSObjectRecords(ar.getSObjectType().getDescribe().getName(),null,null,null,Lightning_Constant.RequiredFieldTypes.ALL_FIELDS_WITH_CUSTOM_FIELDS,sObjectList);
		}

		@isTest static void test_method_two() {
				// Implement test code
				Lightning_ASGMT_DataController.getConfig();

				Lightning_Auxiliary.Filter filter= new Lightning_Auxiliary.Filter();
				filter.searchKey='test';
				filter.relatedObject ='Contact';

				List<Lightning_Auxiliary.Option> options=new List<Lightning_Auxiliary.Option>();
				options.add(new Lightning_Auxiliary.Option('2','2'));
				options.add(new Lightning_Auxiliary.Option('1','1'));
				options.add(new Lightning_Auxiliary.Option('1','1'));
				options.sort();
		}

}